<a href="https://colab.research.google.com/github/nikic2014/Ml/blob/main/%D0%9F%D0%B0%D1%80%D1%86%D0%B5%D0%BF%D1%82%D1%80%D0%BE%D0%BD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [58]:
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler

from sklearn.model_selection import train_test_split

from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import GridSearchCV
from sklearn import datasets

In [47]:
X1, y1 = datasets.load_digits(return_X_y=True)
X1_train, X1_test, y1_train, y1_test = train_test_split(X1, y1, test_size=0.5)

In [12]:
X1[1], y1[1]

(array([ 0.,  0.,  0., 12., 13.,  5.,  0.,  0.,  0.,  0.,  0., 11., 16.,
         9.,  0.,  0.,  0.,  0.,  3., 15., 16.,  6.,  0.,  0.,  0.,  7.,
        15., 16., 16.,  2.,  0.,  0.,  0.,  0.,  1., 16., 16.,  3.,  0.,
         0.,  0.,  0.,  1., 16., 16.,  6.,  0.,  0.,  0.,  0.,  1., 16.,
        16.,  6.,  0.,  0.,  0.,  0.,  0., 11., 16., 10.,  0.,  0.]),
 1)

In [52]:
from sklearn.datasets import fetch_openml

X2, y2 = fetch_openml("mnist_784", version=1, return_X_y=True, as_frame=False)
X2_train, X2_test, y2_train, y2_test = train_test_split(X2, y2, test_size=0.5)

/usr/local/lib/python3.9/dist-packages/sklearn/datasets/_openml.py:968: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


In [53]:
X2_stock, y2_stock = X2.copy(), y2.copy()

In [55]:
X1_stock, y1_stock = X1.copy(), y1.copy()

# Обучение и работа многоклассовой классификации

## А

In [66]:
X1, y1 = X1_stock.copy(), y1_stock.copy()

In [67]:
from sklearn.preprocessing import MinMaxScaler

scaler_mm = MinMaxScaler()

X1 = scaler_mm.fit_transform(X1)

In [68]:
X1_train, X1_test, y1_train, y1_test = train_test_split(X1, y1, test_size=0.5)

In [69]:
clf = MLPClassifier(random_state=1)
clf.fit(X1_train, y1_train)
clf.score(X1_test, y1_test)

0.9988876529477196

In [14]:
clf = MLPClassifier(random_state=1)
clf.fit(X1_train, y1_train)
clf.score(X1_test, y1_test)

0.9699666295884316

In [62]:
params = {'activation': ['relu', 'tanh', 'logistic', 'identity'],
          'solver': ['adam', 'sgd', 'lbfgs'],
          'learning_rate' : ['constant', 'adaptive', 'invscaling'],
          'early_stopping': [False, True],
         }

mlp_grid = GridSearchCV(MLPClassifier(), params)
mlp_grid.fit(X1_train,y1_train)
mlp_grid.score(X1_test, y1_test)

/usr/local/lib/python3.9/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:

1.0

In [22]:
X1_train[1]

array([ 0.,  0.,  1., 14., 16.,  8.,  0.,  0.,  0.,  0.,  2., 10.,  5.,
       14.,  0.,  0.,  0.,  0.,  0.,  2.,  7., 15.,  0.,  0.,  0.,  0.,
        0.,  6., 16., 10.,  0.,  0.,  0.,  0.,  0.,  0.,  3., 14.,  4.,
        0.,  0.,  0., 13.,  0.,  0.,  4., 12.,  0.,  0.,  0., 13.,  6.,
        4.,  8., 13.,  0.,  0.,  0.,  0., 12., 16., 15.,  6.,  0.])

In [27]:
X1[1].reshape(1, -1)

array([[ 0.,  0.,  0., 12., 13.,  5.,  0.,  0.,  0.,  0.,  0., 11., 16.,
         9.,  0.,  0.,  0.,  0.,  3., 15., 16.,  6.,  0.,  0.,  0.,  7.,
        15., 16., 16.,  2.,  0.,  0.,  0.,  0.,  1., 16., 16.,  3.,  0.,
         0.,  0.,  0.,  1., 16., 16.,  6.,  0.,  0.,  0.,  0.,  1., 16.,
        16.,  6.,  0.,  0.,  0.,  0.,  0., 11., 16., 10.,  0.,  0.]])

In [28]:
clf.predict(X1[1].reshape(1, -1))

array([1])

## Б

In [30]:
clf = MLPClassifier(random_state=1)
clf.fit(X2_train, y2_train)
clf.score(X2_test, y2_test)

0.9624857142857143

# Бинарная классификации на чётные и нечётные цифры

In [70]:
X1, y1 = X1_stock.copy(), y1_stock.copy()

In [71]:
from sklearn.preprocessing import MinMaxScaler

scaler_mm = MinMaxScaler()

X1 = scaler_mm.fit_transform(X1)

In [72]:
y1 = y1 % 2
X1_train, X1_test, y1_train, y1_test = train_test_split(X1, y1, test_size=0.5)
y1

array([1, 0, 0, ..., 0, 0, 0])

In [73]:
clf = MLPClassifier(random_state=1)
clf.fit(X1_train, y1_train)
clf.score(X1_test, y1_test)

1.0

In [39]:
clf = MLPClassifier(random_state=1)
clf.fit(X1_train, y1_train)
clf.score(X1_test, y1_test)

0.9777530589543938

In [65]:
params = {'activation': ['relu', 'tanh', 'logistic', 'identity'],
          'solver': ['adam', 'sgd', 'lbfgs'],
          'learning_rate' : ['constant', 'adaptive', 'invscaling'],
          'early_stopping': [False, True],
         }

mlp_grid = GridSearchCV(MLPClassifier(), params)
mlp_grid.fit(X1_train,y1_train)
mlp_grid.score(X1_test, y1_test)

/usr/local/lib/python3.9/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:

0.9988876529477196

In [46]:
y2 = [(int(d) % 2) for d in y2]

X2_train, X2_test, y2_train, y2_test = train_test_split(X2, y2, test_size=0.5)

clf = MLPClassifier(random_state=1)
clf.fit(X2_train, y2_train)
clf.score(X2_test, y2_test)

0.9788571428571429

# Бинарная классификации на '0' и остальные цифры (приведите примеры, когда классификатор ошибается)

In [79]:
X1, y1 = X1_stock.copy(), y1_stock.copy()

In [80]:
scaler_mm = MinMaxScaler()

X1 = scaler_mm.fit_transform(X1)

In [81]:
y1 = y1 == 0
X1_train, X1_test, y1_train, y1_test = train_test_split(X1, y1, test_size=0.5)
y1

array([False,  True,  True, ...,  True,  True,  True])

In [82]:
clf = MLPClassifier(random_state=1)
clf.fit(X1_train, y1_train)
clf.score(X1_test, y1_test)

1.0

In [78]:
clf = MLPClassifier(random_state=1)
clf.fit(X1_train, y1_train)
clf.score(X1_test, y1_test)

0.9988876529477196

In [54]:
y2 = [(int(d) == 0) for d in y2]

X2_train, X2_test, y2_train, y2_test = train_test_split(X2, y2, test_size=0.5)

clf = MLPClassifier(random_state=1)
clf.fit(X2_train, y2_train)
clf.score(X2_test, y2_test)

0.9974571428571428

# Советы
- Многослойный персептрон чувствителен к масштабированию объектов, поэтому настоятельно рекомендуется масштабировать ваши данные. Например, масштабируйте каждый атрибут входного вектора X до [0, 1] или [-1, +1] или стандартизируйте его, чтобы он имел среднее значение 0 и дисперсию 1. Обратите внимание, что для получения значимых результатов необходимо применить то же масштабирование к набору тестов. Вы можете использовать StandardScaler для стандартизации.
-Поиск разумного параметра регуляризации 
 лучше всего использовать GridSearchCV, обычно в диапазоне 10.0 ** -np.arange(1, 7).
- Эмпирически мы заметили, что L-BFGS модели сходятся быстрее и с лучшими решениями на небольших наборах данных. Однако для относительно больших наборов данных Adam очень надежен. Обычно они быстро сходятся и дают довольно хорошую производительность. SGDс другой стороны, с momentum или momentum нестерова могут работать лучше, чем эти два алгоритма, если правильно настроить скорость обучения.